# Numpy
- np.sctypeDict - look at all array dtype`s

In [2]:
# Download numpy for coding:
import numpy as np

In [ ]:
x_values = [1, 2, 45, 654, 'a', 'b', -34, -2, 1.0, 10]

# Create array:
numpy_x_values = np.array(x_values)
# numpy_x_values = np.array(1, 2, 45, 654, ... , 1, 10) <-- not allowed!

print(x_values)
print(type(x_values))
print()
print(numpy_x_values)
print(type(numpy_x_values))
# Change array type:
# numpy_x_values = np.array(x_values, dtype = 'one from np.sctypeDict')

In [ ]:
np.sctypeDict

In [ ]:
# Create zeros and ones arrays:
 # default type = float
empty_array = np.empty(4)
zeros_array = np.zeros(5)
ones_array = np.ones(10, dtype = np.int)

print(empty_array)
print(zeros_array)
print(ones_array)

In [ ]:
# Create range arrays:
range_array = np.arange(10)
print(range_array)
range_array = np.arange(10, 21)
print(range_array)
range_array = np.arange(10, 101,10)
print(range_array)

In [10]:
# Поделить диапазон на число и получить контр. точки:
linspace_array = np.linspace(1, 10, 5)
print(linspace_array)

[ 1.    3.25  5.5   7.75 10.  ]


In [12]:
#multidemensional arrays:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
numpy_matrix = np.array(matrix)

print(matrix)
print()
print(numpy_matrix)
print()
print(np.array([[[1, 2], [3, 4]], [[5,6], [7,8]]]))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
# Zeros and ones with columns:
zeros_array = np.zeros ((2, 3))
# ones.array = np.ones((3,2))

print(zeros_array)
print()
print(np.ones((3, 2)))

[[0. 0. 0.]
 [0. 0. 0.]]

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [31]:
# Reshape arrays (x, y):
example_array = np.array([1, 2, 3, 4, 5, 6])
reshaping = example_array.reshape(2, 3)

example_array2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
reshaping2 = example_array2.reshape(3, 3)

print(reshaping)
print()
print(reshaping2)


[[1 2 3]
 [4 5 6]]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
# x, y axis, graf:
def f(r, c):
  return r*c

some_matrix = np.fromfunction(f,(5, 6))
print(some_matrix)


[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  1.  2.  3.  4.  5.]
 [ 0.  2.  4.  6.  8. 10.]
 [ 0.  3.  6.  9. 12. 15.]
 [ 0.  4.  8. 12. 16. 20.]]


In [36]:
some_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Print some elements from array:
print(some_array[0])

# Change element in array:
some_array[7] = 666

print(some_array)

1
[  1   2   3   4   5   6   7 666   9  10]


In [46]:
# Create multidimensional array:
array_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 'a', 'b']])

# Return array from multi-array:
print(array_matrix[0])
print()

# Return element from multi-array:
print(array_matrix[2, 1])
print()

# Change element in multi-array:
array_matrix[2, 2] = 777

# Change array to new array:
array_matrix[0] = np.array([123, 3, 321])
print(array_matrix)

['1' '2' '3']

a

[['123' '3' '321']
 ['4' '5' '6']
 ['7' 'a' '777']]


In [50]:
# Slice array elements:
sliced_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(sliced_array[:5])
print(sliced_array[5:10])
print(sliced_array[-2])

sliced_array[5:10] = 6
# sliced_array[5:10] = np.array([1,2]) <-- not allowed
print(sliced_array)

[1 2 3 4 5]
[ 6  7  8  9 10]
9
[1 2 3 4 5 6 6 6 6 6]


In [60]:
array_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 'a', 'b']])

print(array_matrix[0,0:6])
print(array_matrix[:,:])
print(array_matrix[:,1])
print(array_matrix[:,1:3])

['1' '2' '3']
[['1' '2' '3']
 ['4' '5' '6']
 ['7' 'a' 'b']]
['2' '5' 'a']
[['2' '3']
 ['5' '6']
 ['a' 'b']]


In [66]:
# arrays operations: + - * / % // ** :
arithmetic_array = np.array([1, 2, 3, 4, 5])
result = arithmetic_array * 2

# Work just if the same amount of numbers (indexes):
result_2 = arithmetic_array + np.array([6,7,8,9,10])
 # allowed:
result_3 = arithmetic_array[:3] + np.array([11,12,13])

print(arithmetic_array)
print(result)
print(result_2)
print(result_3)

[1 2 3 4 5]
[ 2  4  6  8 10]
[ 7  9 11 13 15]
[12 14 16]


In [ ]:
arithmetic_matrix = np.array([[1,2,3],[4,5,6]])
